// src/components/explorer/ExplorerBreadcrumb.tsx
/**
 * ExplorerBreadcrumb — home icon + segment trail (baseline
 * ExplorerBreadcrumb.vue). explorer mode: every segment clickable; doc mode:
 * current page non-clickable. >3 segments collapse to ellipsis.
 */
import { useLocation, useNavigate } from "react-router-dom";
import { useExplorerStore } from "@/stores/explorer";

export default function ExplorerBreadcrumb({
	context = "doc",
}: {
	context?: "doc" | "explorer";
}) {
	const location = useLocation();
	const navigate = useNavigate();
	const explorerPath = useExplorerStore((s) => s.currentPath);
	const setCurrentPath = useExplorerStore((s) => s.setCurrentPath);

	const fullPath =
		context === "explorer"
			? explorerPath
			: location.pathname.replace(/\.html$/, "");

	// doc-context on the explorer home page → hidden (baseline suppression)
	if (
		context === "doc" &&
		(location.pathname === "/" || location.pathname === "/index")
	) {
		return null;
	}

	const segments = fullPath
		.split("/")
		.filter(Boolean)
		.map((s) => {
			try {
				return decodeURIComponent(s);
			} catch {
				return s;
			}
		});

	if (segments.length === 0 && context === "doc") return null;

	const visible =
		segments.length <= 3 ? segments : ["…", ...segments.slice(-2)];
	const isCurrent = (i: number) =>
		context !== "explorer" && i === segments.length - 1;

	const go = (path: string) => {
		if (context === "explorer") {
			setCurrentPath(path);
		}
		navigate(path === "/" ? "/" : `/?path=${encodeURIComponent(path)}`);
	};

	let acc = "";

	return (
		<nav className="breadcrumb" aria-label="面包屑">
			<span
				className="crumb-item crumb-home"
				title="回到首页"
				onClick={() => go("/")}
			>
				🏠
			</span>
			{visible.map((seg, i) => {
				if (seg === "…") {
					return (
						<span
							key="ellipsis"
							className="crumb-item ellipsis"
							title={fullPath}
						>
							…
						</span>
					);
				}
				const idx = i === 0 && visible[0] === "…" ? segments.length - 2 : i;
				const prev = acc;
				acc = prev ? `${prev}/${seg}` : seg;
				const segPath = `/${acc}`;
				const isLast = i === visible.length - 1;
				return (
					<span key={segPath} className="crumb-item-group">
						<span className="crumb-separator">/</span>
						{isLast && isCurrent(idx) ? (
							<span className="crumb-item current">{seg}</span>
						) : (
							<span
								className="crumb-item text"
								title={segPath}
								onClick={() => go(segPath)}
							>
								{seg}
							</span>
						)}
					</span>
				);
			})}
		</nav>
	);
}

// docs/.vitepress/components/ExplorerBreadcrumb.vue
<template>
  <div class="breadcrumb" v-if="visibleSegments.length || isExplorer">
    <a href="javascript:void(0)" class="crumb-item" @click="go('/')">🏠</a>

    <template v-for="(segment, idx) in visibleSegments" :key="idx">
      <span class="separator">/</span>
      <span v-if="segment.isEllipsis" class="crumb-item ellipsis" :title="fullPath">...</span>
      <span v-else-if="segment.isCurrent" class="crumb-item text current">{{ segment.name }}</span>
      <a v-else href="javascript:void(0)" class="crumb-item text" @click="go(segment.path)">{{ segment.name }}</a>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vitepress'
import { explorerStore } from '../explorerStore'

const router = useRouter()
const route = useRoute()

const isExplorer = computed(() => {
  const p = route.path.replace(/\.html$/, '')
  return p === '/' || p === '/index'
})

const fullPath = computed(() => {
  if (isExplorer.value) return explorerStore.currentPath
  return route.path.replace(/\.html$/, '')
})

const visibleSegments = computed(() => {
  const path = fullPath.value
  if (!path || path === '/') return []

  const parts = path.replace(/^\/+|\/+$/g, '').split('/').map(decodeURIComponent)
  const lastIdx = parts.length - 1

  const makeSeg = (i: number) => ({
    name: parts[i],
    // On md page the last segment is the file itself, not a dir — mark
    // as non-clickable current crumb. In explorer mode every segment is a
    // dir and remains clickable.
    path: '/' + parts.slice(0, i + 1).join('/'),
    isEllipsis: false,
    isCurrent: !isExplorer.value && i === lastIdx
  })

  if (parts.length <= 3) {
    return parts.map((_, i) => makeSeg(i))
  }
  return [
    { name: '...', path: '', isEllipsis: true, isCurrent: false },
    makeSeg(lastIdx - 1),
    makeSeg(lastIdx)
  ]
})

function go(path: string) {
  router.go(`/?path=${encodeURIComponent(path)}`)
}
</script>

<style scoped>
.breadcrumb {
  display: flex;
  align-items: center;
  font-size: 16px;
  white-space: nowrap;
  overflow: hidden;
}
.crumb-item {
  color: var(--vp-c-text-2);
  text-decoration: none;
  transition: color 0.2s;
}
.crumb-item.text {
  max-width: 120px;
  overflow: hidden;
  text-overflow: ellipsis;
}
.crumb-item:hover {
  color: var(--vp-c-brand);
}
.separator {
  color: var(--vp-c-text-3);
  margin: 0 6px;
}
.ellipsis {
  cursor: default;
}
.ellipsis:hover {
  color: var(--vp-c-text-2);
}
.crumb-item.current {
  color: var(--vp-c-text-1);
  font-weight: 600;
  cursor: default;
}
</style>
