// src/components/explorer/ExplorerTopBar.tsx
/**
 * ExplorerTopBar — [ProfileToggle] [Breadcrumb] [spacer] [SortControl]
 * (baseline ExplorerTopBar.vue).
 */
import ProfileToggle from "../layout/ProfileToggle";
import ExplorerBreadcrumb from "./ExplorerBreadcrumb";
import SortControl from "./SortControl";

export default function ExplorerTopBar() {
	return (
		<div className="explorer-topbar">
			<ProfileToggle />
			<ExplorerBreadcrumb context="explorer" />
			<div className="topbar-spacer" />
			<SortControl />
		</div>
	);
}

// docs/.vitepress/components/ExplorerTopBar.vue
<template>
  <div class="explorer-topbar">
    <ProfileToggle />
    <ExplorerBreadcrumb context="explorer" />
    <div class="spacer"></div>
    <SortControl />
  </div>
</template>

<script setup lang="ts">
import ProfileToggle from './ProfileToggle.vue'
import ExplorerBreadcrumb from './ExplorerBreadcrumb.vue'
import SortControl from './SortControl.vue'
</script>

<style scoped>
.explorer-topbar {
  flex-shrink: 0;
  border-bottom: 1px solid var(--vp-c-divider);
  padding: 12px 24px;
  display: flex;
  align-items: center;
  gap: 12px;
}
.spacer {
  flex: 1;
}
@media (max-width: 959px) {
  .explorer-topbar {
    padding: 12px 16px;
  }
}
</style>
