// src/components/explorer/SortControl.tsx
/**
 * SortControl — name/date select + asc/desc toggle (baseline SortControl.vue).
 * Persists to `explorer:sort` via the store.
 */
import { useExplorerStore } from "@/stores/explorer";

export default function SortControl() {
	const sortKey = useExplorerStore((s) => s.sortKey);
	const sortOrder = useExplorerStore((s) => s.sortOrder);
	const setSort = useExplorerStore((s) => s.setSort);

	return (
		<div className="sort-control">
			<select
				className="sort-select"
				value={sortKey}
				onChange={(e) => setSort(e.target.value as "name" | "date", sortOrder)}
				title="排序方式"
				aria-label="排序方式"
			>
				<option value="name">名称</option>
				<option value="date">日期</option>
			</select>
			<button
				className="sort-order"
				title={sortOrder === "asc" ? "降序" : "升序"}
				aria-label={sortOrder === "asc" ? "切换为降序" : "切换为升序"}
				onClick={() => setSort(sortKey, sortOrder === "asc" ? "desc" : "asc")}
			>
				{sortOrder === "asc" ? "↑" : "↓"}
			</button>
		</div>
	);
}

// docs/.vitepress/components/SortControl.vue
<template>
  <div class="sort-control">
    <select v-model="explorerStore.sortKey" @change="save" class="sort-select">
      <option value="name">名称</option>
      <option value="date">日期</option>
    </select>
    <button class="sort-order" @click="toggleOrder" :title="explorerStore.sortOrder === 'asc' ? '升序' : '降序'">
      {{ explorerStore.sortOrder === 'asc' ? '↑' : '↓' }}
    </button>
  </div>
</template>

<script setup lang="ts">
import { explorerStore } from '../explorerStore'

const toggleOrder = () => {
  explorerStore.sortOrder = explorerStore.sortOrder === 'asc' ? 'desc' : 'asc'
  save()
}

const save = () => {
  if (typeof window !== 'undefined') {
    localStorage.setItem('explorer:sort', `${explorerStore.sortKey}:${explorerStore.sortOrder}`)
  }
}
</script>

<style scoped>
.sort-control {
  --sort-item-width: 7ch;
  --sort-item-px: 1ch;
  display: flex;
  align-items: center;
  gap: 4px;
  background: var(--vp-c-default-soft);
  border-radius: 6px;
  padding: 2px 4px;
}
.sort-select {
  background: transparent;
  border: none;
  color: var(--vp-c-text-2);
  font-size: 13px;
  outline: none;
  cursor: pointer;
  padding: 4px var(--sort-item-px);
  min-width: var(--sort-item-width);
  box-sizing: border-box;
}
.sort-order {
  background: transparent;
  border: none;
  color: var(--vp-c-text-2);
  cursor: pointer;
  padding: 4px var(--sort-item-px);
  min-width: auto;
  box-sizing: border-box;
  border-radius: 4px;
}
.sort-order:hover {
  background: var(--vp-c-default-mute);
  color: var(--vp-c-text-1);
}
</style>
